// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SolarMetrics;

#nullable disable

namespace SolarMetrics.Migrations
{
    [DbContext(typeof(SolarMetricsContext))]
    partial class SolarMetricsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolarMetrics.Infrastructure.Persistence.Entitites.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("SM_USUARIO", (string)null);
                });

            modelBuilder.Entity("SolarMetrics.Infrastructure.Persistence.Entitites.Monitoramento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("MaximaLeitura")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("MediaLeitura")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("ValorLido")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("SM_MONITORAMENTO", (string)null);
                });

            modelBuilder.Entity("SolarMetrics.Infrastructure.Persistence.Entitites.PainelSolar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("DataFabricacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Eficiencia")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("PotenciaMaxima")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid>("SistemaId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("SistemaId");

                    b.ToTable("SM_PAINEL_SOLAR", (string)null);
                });

            modelBuilder.Entity("SolarMetrics.Infrastructure.Persistence.Entitites.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<Guid>("SistemaId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("Id");

                    b.HasIndex("SistemaId");

                    b.ToTable("SM_SENSOR", (string)null);
                });

            modelBuilder.Entity("SolarMetrics.Infrastructure.Persistence.Entitites.Sistema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("DataInstalacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("NomeInstalacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("PotenciaTotal")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("SM_SISTEMA", (string)null);
                });

            modelBuilder.Entity("SolarMetrics.Infrastructure.Persistence.Entitites.Monitoramento", b =>
                {
                    b.HasOne("SolarMetrics.Infrastructure.Persistence.Entitites.Sensor", "Sensor")
                        .WithMany("Monitoramentos")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SolarMetrics.Infrastructure.Persistence.Entitites.PainelSolar", b =>
                {
                    b.HasOne("SolarMetrics.Infrastructure.Persistence.Entitites.Sistema", "Sistema")
                        .WithMany("PaineisSolares")
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("SolarMetrics.Infrastructure.Persistence.Entitites.Sensor", b =>
                {
                    b.HasOne("SolarMetrics.Infrastructure.Persistence.Entitites.Sistema", "Sistema")
                        .WithMany("Sensores")
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("SolarMetrics.Infrastructure.Persistence.Entitites.Sistema", b =>
                {
                    b.HasOne("SolarMetrics.Infrastructure.Persistence.Entitites.Cliente", "Cliente")
                        .WithMany("Sistemas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SolarMetrics.Infrastructure.Persistence.Entitites.Cliente", b =>
                {
                    b.Navigation("Sistemas");
                });

            modelBuilder.Entity("SolarMetrics.Infrastructure.Persistence.Entitites.Sensor", b =>
                {
                    b.Navigation("Monitoramentos");
                });

            modelBuilder.Entity("SolarMetrics.Infrastructure.Persistence.Entitites.Sistema", b =>
                {
                    b.Navigation("PaineisSolares");

                    b.Navigation("Sensores");
                });
#pragma warning restore 612, 618
        }
    }
}
